# Generated by Django 4.2 on 2023-04-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cockteil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteCocktails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idDrink', models.IntegerField(blank=True, null=True)),
                ('strDrink', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('original_dict', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ingredientstype',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
